# Exercise 1. - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Check out [Occupation Exercises Video Tutorial](https://www.youtube.com/watch?v=W8AB5s-L3Rw&list=PLgJhDSE2ZLxaY_DigHeiIDC1cD09rXgJv&index=4) to watch a data scientist go through the exercises

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

In [3]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user'

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [4]:
users = pd.read_csv(url, sep='|', index_col='user_id')

### Step 4. See the first 25 entries

In [5]:
users.head(25)

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

### Step 5. See the last 10 entries

In [6]:
users.tail(10)

         age gender     occupation zip_code
user_id
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

### Step 6. What is the number of observations in the dataset?

In [25]:
len(users)

943

### Step 7. What is the number of columns in the dataset?

In [24]:
users.shape[1]

4

### Step 8. Print the name of all the columns.

### Step 9. How is the dataset indexed?

### Step 10. What is the data type of each column?

### Step 11. Print only the occupation column

### Step 12. How many different occupations are in this dataset?

### Step 13. What is the most frequent occupation?

### Step 14. Summarize the DataFrame.

In [5]:
users.describe()

              age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

### Step 15. Summarize all the columns

In [6]:
users.describe(include='all')

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [9]:
users['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

In [10]:
round(users['age'].mean(), 2)

np.float64(34.05)

### Step 18. What is the age with least occurrence?

In [15]:
age_occurrence = users['age'].value_counts()
age_occurrence[age_occurrence == age_occurrence.min()]

age
7     1
66    1
11    1
10    1
73    1
Name: count, dtype: int64

# Exercise 2. - Filtering and Sorting Data

Check out [Euro 12 Exercises Video Tutorial](https://youtu.be/iqk5d48Qisg) to watch a data scientist go through the exercises

This time we are going to pull data directly from the internet.

### Step 1. Import the necessary libraries

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/kflisikowsky/pandas_exercises/refs/heads/main/Euro_2012_stats_TEAM.csv).

### Step 3. Assign it to a variable called euro12.

### Step 4. Select only the Goal column.

### Step 5. How many team participated in the Euro2012?

### Step 6. What is the number of columns in the dataset?

### Step 7. View only the columns Team, Yellow Cards and Red Cards and assign them to a dataframe called discipline

### Step 8. Sort the teams by Red Cards, then to Yellow Cards

### Step 9. Calculate the mean Yellow Cards given per Team

### Step 10. Filter teams that scored more than 6 goals

### Step 11. Select the teams that start with G

### Step 12. Select the first 7 columns

### Step 13. Select all columns except the last 3.

### Step 14. Present only the Shooting Accuracy from England, Italy and Russia

# Exercise 3. - GroupBy

### Introduction:

GroupBy can be summarized as Split-Apply-Combine.

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Check out this [Diagram](http://i.imgur.com/yjNkiwL.png)  

Check out [Alcohol Consumption Exercises Video Tutorial](https://youtu.be/az67CMdmS6s) to watch a data scientist go through the exercises


### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

In [3]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv'
df = pd.read_csv(url)

### Step 3. Assign it to a variable called drinks.

In [4]:
drinks = df

### Step 4. Which continent drinks more beer on average?

### Step 5. For each continent print the statistics for wine consumption.

### Step 6. Print the mean alcohol consumption per continent for every column

### Step 7. Print the median alcohol consumption per continent for every column

In [8]:
drinks.groupby('continent').median(numeric_only=True)

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,32.0,3.0,2.0,2.30
AS,17.5,16.0,1.0,1.20
EU,219.0,122.0,128.0,10.00
OC,52.5,37.0,8.5,1.75
SA,162.5,108.5,12.0,6.85

### Step 8. Print the mean, min and max values for spirit consumption.
#### This time output a DataFrame

In [6]:
drinks.groupby('continent')['spirit_servings'].agg(['mean', 'min', 'max'])

                 mean  min  max
continent
AF          16.339623    0  152
AS          60.840909    0  326
EU         132.555556    0  373
OC          58.437500    0  254
SA         114.750000   25  302